name: FPL ETL + dbt Pipeline

on:
  schedule:
    - cron: "0 23 * * *"   # Run daily at 06:00 WIB (23:00 UTC)
  workflow_dispatch:        # Allow manual run

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    - name: Setup GCP credentials ðŸ”‘
      run: |
        # Menggunakan 'echo' dengan kutip tunggal ('...') untuk menulis JSON multi-line 
        # (termasuk karakter newline di private_key) langsung ke file.
        echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' > $GITHUB_WORKSPACE/key.json
        
        # Menetapkan lokasi file sebagai variabel lingkungan agar Google libraries dapat menemukannya
        echo "GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/key.json" >> $GITHUB_ENV

    - name: Run ETL (Extract + Load)
      run: |
        python etl/extract_load.py

    - name: Setup dbt
      run: |
        pip install dbt-bigquery

    - name: Run dbt models
      working-directory: ./dbt
      run: |
        dbt deps
        dbt run
        dbt test
